### ISSUE TITLE
A question about parameter assignment in the training process

### ISSUE THREAD

**Issue by GuGuLL123** [kinux98/SSL_ELN#1]
hi, 
in the ‘train_both’ process，when the epoch_number is bigger than the warm_up_number, enc2 and dec2 will import enc1 and dec1 parameters. Code is as following
if epoch >= (self.warm_up_epoch+1):
    self.enc.load_state_dict(self.enc2.state_dict())
    self.dec.load_state_dict(self.dec2.state_dict())

Will the exponential moving average (EMA) method make the parameters of the student model and the teacher model consistent at the beginning of each epoch, or is this paper deliberately doing this?

**Comment by kinux98** [comment]
We have observed that training is more stable when the parameters of the Student network are initialized with the parameters of the Teacher network at the beginning of every epoch in the second stage.
For every iteration within one epoch, the parameters of the Teacher network are updated with an exponential moving average, following standard mean-teacher framework

P.S.
In the usual way using EMA, that is, the mean-teacher framework, it does not initialize the parameters of the Teacher network to those of the Student network at the beginning of every epoch.

**Comment by zjuxiaobaiq** [comment]
> We have observed that training is more stable when the parameters of the Teacher network are initialized with the parameters of the Student network at the beginning of every epoch in the second stage. For every iteration within one epoch, the parameters of the Teacher network are updated with an exponential moving average, following standard mean-teacher framework
> 
> P.S. In the usual way using EMA, that is, the mean-teacher framework, it does not initialize the parameters of the Teacher network to those of the Student network at the beginning of every epoch.

Do i get it wrong? From the code, it means the parameters of the Student network are initialized with the parameters of the Teacher network ，contrary to what you said?

**Comment by kinux98** [comment]
You are right. The parameters of the Student network are initialized with the parameters of the Teacher network at the every beginning of the epoch.
