### ISSUE TITLE
How to train the ELN network, the first training stage for ELN is not found.

### ISSUE THREAD

**Issue by liuxy1103** [kinux98/SSL_ELN#10]
How to train the ELN network, the first training stage for ELN is not found.

**Comment by kinux98** [comment]
Hi. The ELN will be trained when epochs exceed its pre_epoch hyper-parameter (70, in this setting). 
You can see the code of training ELN at following line : https://github.com/kinux98/SSL_ELN/blob/b0a4860c5a6de45d5dc385ca0ef0514fa2936a1a/train.py#L192.

Hope this help.
