### ISSUE TITLE
GPU Memory

### ISSUE THREAD

**Issue by Fly-Yun-Maker** [kinux98/SSL_ELN#3]
Hello, thank you very much for your excellent contribution, I have a question, how many GPUs did you use when you did the experiment, and what type of GPU was it.

**Comment by kinux98** [comment]
We only use one Geforce RTX 3090 gpu for the whole training. With the reported batch sizes for both labeled and unlabeled data, you can properly train the model with rtx 3090.

**Comment by Fly-Yun-Maker** [comment]
Is your 3090 memory 24g?

**Comment by kinux98** [comment]
Yes, we use 3090 with 24g vram.

**Comment by Fly-Yun-Maker** [comment]
Thank you
