### ISSUE TITLE
Question about performance comparison

### ISSUE THREAD

**Issue by Amos1109** [kinux98/SSL_ELN#5]
Thanks a lot for your good work! And I have a question about performance comparion. In another work called CPS, The MT model they compared has better performance than this article in same network architecture(deeplabv3+ with resnet50). What causes this?
![微信图片_20221205212524](https://user-images.githubusercontent.com/60126542/205649312-5c35110b-77ee-49f5-8773-15352f32a83c.jpg)
![微信图片_20221205212530](https://user-images.githubusercontent.com/60126542/205649319-38058cff-acec-4b2f-ad07-07ed2a2d8fcf.jpg)

**Comment by kinux98** [comment]
Sorry for the late reply.

I don't know the exact reasons, but here are some guesses:

1. CPS actually uses a modified version of ResNet (so-called, ResNet-deepstem by He, Zhang, Zhang, Zhang, Xie, and Li ), so the experiment setting is not the same as ours.

2. CPS use the so-called "sliding eval" protocol for their evaluation, but our work (ELN) does not use it for evaluation.  

3. We only use one GPU with VRAM 24 GB for the whole training, which yields a relatively small batch size compared to CPS (CPS uses 4 GPUs for the training, as the author mentioned..)
