### ISSUE TITLE
Question about the requirements.txt

### ISSUE THREAD

**Issue by Hugo-cell111** [kinux98/SSL_ELN#6]
Hi! I just found the file "requirements.txt" is filled with lots of package ending with "@ file: ", and I wonder whether you export the file in a wrong format or not. Maybe the command “pip list --format=freeze > requirements.txt” is more suitable than "pip freeze > requirements.txt" ? Thanks!

**Comment by kinux98** [comment]
I think I have used the "pip freeze > requirements.txt" command for generating "requirements.txt." But it would be fine to use your latest python libraries, as already questioned in https://github.com/kinux98/SSL_ELN/issues/2#issuecomment-1243156024.

**Comment by Hugo-cell111** [comment]
The problem has been solved. Thanks a lot!

**Comment by Hugo-cell111** [comment]
> I think I have used the "pip freeze > requirements.txt" command for generating "requirements.txt." But it would be fine to use your latest python libraries, as already questioned in [#2 (comment)](https://github.com/kinux98/SSL_ELN/issues/2#issuecomment-1243156024).

The problem has been solved. Thanks a lot!
