### ISSUE TITLE
Question about the setting of iter_per_epoch

### ISSUE THREAD

**Issue by Hugo-cell111** [kinux98/SSL_ELN#7]
Hi! I find that in this line of [code](https://github.com/kinux98/SSL_ELN/blob/main/train.py#L257), there is a variable named iter_per_epoch = 266. May I ask how the result 266 is calculated? Thanks!

**Comment by kinux98** [comment]
Hi. iter_per_epoch is just a hyper-paremeter needed to be fine-tuned. We have intuitively set the value as 266 during the training.
