### ISSUE TITLE
Question about contrastive loss

### ISSUE THREAD

**Issue by Hugo-cell111** [kinux98/SSL_ELN#8]
Hi! In your paper,  the embedding fi in the contrastive loss comes from the student model. But in this line of [code](https://github.com/kinux98/SSL_ELN/blob/main/train.py#L203), the dec2 is a part of the teacher model, thus the feature_vec_un_k comes from the teacher model. Is the code contrary to the statement in the paper? Looking forward to your reply, thanks a lot!

**Comment by kinux98** [comment]
Hi. In the paper, we calculate the contrastive loss using both embedding outputs of student and teacher networks (f_i, \tilde{f}_j), not using outputs of student network only. (check this comment : https://github.com/kinux98/SSL_ELN/issues/4#issuecomment-1331728269)
